<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong>
        Importando bibliotecas
    </strong>
</p>

In [43]:
import pandas as pd
import xlwings as xw

#bibliotecas comuns para layout
#pygame
#tkinter
#custom tkinter - Mais utilizada

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Lendo base de dados
    </strong>
</p>

In [44]:
nome_arquivo = 'base_entregas_brutas'

def ler_arquivo(nome_arquivo):
    try:
        df = pd.read_excel(f'dados/{nome_arquivo}.xlsx')
        return df

    except FileNotFoundError as e:
        print(f'Erro: {e}')

def criar_atualizar_arquivo(nome_arquivo, df_tratado=''):
    df_tratado.to_excel(f'dados/{nome_arquivo}.xlsx'
                        )

In [45]:
df = ler_arquivo('base_entregas_brutas')

<p style="font-size: 1.1rem; color: #9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Informações gerais
    </strong>
</p>

In [46]:
#df.shape()
#df.info()

df.sample(5, random_state=42) #amostragem diferente de linhas
# pq 42?

,id_entrega,filial,cliente,status,descricao_entrega,tipo_servico,valor_frete,data_postagem,prazo_previsto,dias_atraso
1126,1838,MG,Amazon,ATRASADO,Entrega com atraso por chuva,NaN,153.43,2026-01-17 19:55:58,3.0,NaN
79,1199,PR,Americanas,Entregue,Entrega reagendada,EXPRESSA,134.88,2026-01-16 19:55:58,7.0,2.0
3260,3143,SC,Americanas,atrasado,Problema operacional na rota,EXPRESSA,58.41,2026-01-15 19:55:58,NaN,0.0
1736,601,MG,NaN,Entregue,Entrega normal,EXPRESSA,181.55,2026-01-23 19:55:58,3.0,0.0
4526,979,RS,Shopee,EM TRANSITO,Entrega EXPRESSA,EXPRESS,140.26,2026-01-06 19:55:58,NaN,0.0

<p style="font-size: 1.1rem; color: #9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Tratamento - Dados ausentes        
    </strong>
</p>

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Por segurança, criamos uma copia do DF       
    </strong>
</p>

In [47]:
df_tratado = df.copy()

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Filial 
    </strong>
</p>

In [48]:
#pegando todas a linhas, mas não sabe qual coluna deve informar qual coluna quer
df_tratado.loc[: , 'filial'] = df_tratado['filial'].fillna('Não Informada') #vazio
#df.replace() para substituir alguma informação

df_tratado['filial'].sample(10)

2983               MG
2501               SC
125     Não Informada
2069               RJ
2132               SC
3132               MG
4929               SP
4535    Não Informada
4553               SC
1073               RS
Name: filial, dtype: str

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Cliente 
    </strong>
</p>

In [49]:
df_tratado.loc[: , 'cliente'] = df_tratado['cliente'].fillna('Outros') #vazio

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Dias de atraso 
    </strong>
</p>

In [50]:
df_tratado.loc[: , 'dias_atraso'] = df_tratado['dias_atraso'].fillna(0) #vazio

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Prazo previsto 
    </strong>
</p>

In [51]:
df_tratado.loc[: , 'prazo_previsto'] = df_tratado['prazo_previsto'].fillna(
    df_tratado['prazo_previsto'].median()
)

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Tratamento - Duplicadas
    </strong>
</p>

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Verificando duplicadas com base no ID 
    </strong>
</p>

In [52]:
df_tratado.duplicated(subset=['id_entrega']).sum()

np.int64(2334)

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Removendo duplicadas, mantendo a primeira ocorrencia
    </strong>
</p>

In [53]:
df_tratado.drop_duplicates(subset=['id_entrega'],inplace = True)

#df_tratado.drop_duplicates(subset=['id_entrega']

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Verificando duplicadas com base no ID 
    </strong>
</p>

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Tratamento - Tipagem correta para ID
    </strong>
</p>

In [54]:
df_tratado['id_entrega'] = df_tratado['id_entrega'].astype('Int64')
df_tratado['prazo_previsto'] = df_tratado['prazo_previsto'].astype('Int64')
df_tratado['dias_atraso'] = df_tratado['dias_atraso'].astype('Int64')

In [55]:
df_tratado.dtypes #retorna os tipos de dados

id_entrega                    Int64
filial                          str
cliente                         str
status                          str
descricao_entrega               str
tipo_servico                    str
valor_frete                 float64
data_postagem        datetime64[us]
prazo_previsto                Int64
dias_atraso                   Int64
dtype: object

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Tratamento - Padronização e Normalização
    </strong>
</p>

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Removendo espaços e alterando para caixa alta 
    </strong>
</p>

In [56]:
df_tratado['status'] = df_tratado['status'].str.strip().str.upper() #remover espaço antes e no final do texto da celula

df_tratado['tipo_servico'] = df_tratado['tipo_servico'].str.strip().str.upper() #remover espaço antes e no final do texto da celula

df_tratado['cliente'] = df_tratado['cliente'].str.strip().str.upper() #remover espaço antes e no final do texto da celula

df_tratado.head()

,id_entrega,filial,cliente,status,descricao_entrega,tipo_servico,valor_frete,data_postagem,prazo_previsto,dias_atraso
0,2870,PR,AMAZON,ENTREGUE,Entrega realizada no prazo,NORMAL,274.75,2026-01-08 19:55:58,2,0
1,930,RJ,MERCADO LIVRE,ENTREGUE,Entrega reagendada,NORMAL,81.90,2026-01-11 19:55:58,3,0
2,1934,MG,AMAZON,ENTREGUE,NaN,NaN,291.76,2026-01-13 19:55:58,5,3
3,940,MG,AMAZON,ATRASADO,Entrega reagendada,ECONÔMICO,40.89,2026-01-14 19:55:58,2,0
4,1969,SC,MERCADO LIVRE,EM TRANSITO,Entrega com atraso por chuva,NaN,229.75,2026-01-19 19:55:58,3,0

<p style="font-size: 1.1rem; color: #00d9ff; font-family: monospace ">
    <strong>
        Status 
    </strong>
</p>

In [57]:
#chaves: como está : como ficará
mapa_status = {
    'EM TRÂNSITO' : 'EM TRANSITO',
    'EM TRANSITO' : 'EM TRANSITO',
    'ENTREGUE'    : 'ENTREGUE',
    'EM TRÂNZITO' : 'EM TRANSITO',
    'EM TRANZITO' : 'EM TRANSITO',
    'ATRAZADO'    : 'ATRASADO',
    'ATRASADO'    : 'ATRASADO'
}

df_tratado['status'] = df_tratado['status'].map(mapa_status)

df_tratado.sample(frac=0.15) #frac retorna uma porcentagem de linhas para amostra

,id_entrega,filial,cliente,status,descricao_entrega,tipo_servico,valor_frete,data_postagem,prazo_previsto,dias_atraso
351,749,SP,AMAZON,ATRASADO,Problema operacional na rota,ECONÔMICO,75.79,2026-01-17 19:55:58,7,3
1604,2677,RJ,SHOPEE,ATRASADO,NaN,EXPRESS,144.82,2026-02-01 19:55:58,3,2
2075,965,Não Informada,MERCADO LIVRE,NaN,Entrega realizada no prazo,ECONÔMICO,15.11,2026-01-06 19:55:58,5,2
2322,1211,Não Informada,MERCADO LIVRE,ENTREGUE,Entrega normal,NORMAL,349.65,2026-01-10 19:55:58,2,0
4116,2590,SP,SHOPEE,ATRASADO,Entrega com atraso por chuva,EXPRESSA,230.43,2026-01-29 19:55:58,2,0
...,...,...,...,...,...,...,...,...,...,...
4736,1288,SC,AMERICANAS,NaN,Entrega realizada no prazo,NORMAL,343.27,2026-02-01 19:55:58,3,2
94,955,SP,MERCADO LIVRE,EM TRANSITO,Extravio temporário,NaN,33.75,2026-01-31 19:55:58,1,3
461,1412,RJ,MERCADO LIVRE,ENTREGUE,Extravio temporário,ECONÔMICO,216.50,2026-01-06 19:55:58,7,2
1757,2525,Não Informada,SHOPEE,ATRASADO,Entrega EXPRESSA,EXPRESS,315.92,2026-01-04 19:55:58,3,0
487,1717,SP,OUTROS,EM TRANSITO,Cliente ausente no local,ECONÔMICO,336.67,2026-01-22 19:55:58,1,2

Criando coluna calculada

In [58]:
df_tratado['data_prevista'] = (
    df_tratado['data_postagem'] +
    pd.to_timedelta(df_tratado['prazo_previsto'],unit='D') # sempre D para dias | M mês | Y ano >> Sempre tem que converter em uma unidade de tempo
)

df_tratado[[
    'data_postagem',
    'prazo_previsto',
    'data_prevista'
]
]

           data_postagem  prazo_previsto       data_prevista
0    2026-01-08 19:55:58               2 2026-01-10 19:55:58
1    2026-01-11 19:55:58               3 2026-01-14 19:55:58
2    2026-01-13 19:55:58               5 2026-01-18 19:55:58
3    2026-01-14 19:55:58               2 2026-01-16 19:55:58
4    2026-01-19 19:55:58               3 2026-01-22 19:55:58
...                  ...             ...                 ...
5177 2026-01-29 19:55:58               5 2026-02-03 19:55:58
5184 2026-01-14 19:55:58               2 2026-01-16 19:55:58
5188 2026-01-08 19:55:58               3 2026-01-11 19:55:58
5190 2026-01-06 19:55:58               3 2026-01-09 19:55:58
5194 2026-01-14 19:55:58               2 2026-01-16 19:55:58

[2866 rows x 3 columns]

In [59]:
hoje =pd.Timestamp.today().normalize()

df_tratado['Atraso'] = (
    hoje - df_tratado['data_prevista']
).dt.days

df_tratado['Atraso'] = df_tratado['Atraso'].clip(lower=0)

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Prazo previsto de acordo com a filial
    </strong>
</p>

In [60]:
#ALT+SHIFT+SETA PARA CIMA para duplicar as celulas
#Após salvar a celula basta clicar na letra B para abrir uma nova celula

df_tratado.loc[
    (df_tratado['cliente'] == "SHOPEE") &
    (df_tratado['filial'] == "RJ") ,
    'prazo_previsto'
] = 5

#df_tratado.loc[
 #   (df_tratado['cliente'] == "AMAZON") &
  #  (df_tratado['filial'].isin(["RJ", 'SP'])) ,
  #  'prazo_previsto'
#] = 5


df_tratado.loc[
    (df_tratado['cliente'] == "AMAZON") &
    (df_tratado['filial'] .isin(["MG", 'SP'])) ,
    'prazo_previsto'
] = 2

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Atualizando arquivo para executar fórmulas
    </strong>
</p>

In [ ]:
#criar uma instancia que vai abrir o arquivo e a visibilidade vai mostrar se o excel abriu
app = xw.App(visible=False)

#qual arquivo vai abrir - Informar sempre o caminho completo
wb = xw.Book(f'dados/base2.xlsx')

#forçar os calculos da planilha
wb.app.calculate()

#salvar o excel
wb.save()

#fechar o excel
wb.close()

#encerra a programação
app.quit()

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/><br/><br/><br/><br/>
        Salvando arquivo tratado
    </strong>
</p>

In [62]:
criar_atualizar_arquivo('base2', df_tratado=df_tratado)

In [63]:
ler_arquivo('nome_arquivo')

Erro: [Errno 2] No such file or directory: 'dados/nome_arquivo.xlsx'