<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong>
        Importando bibliotecas
    </strong>
</p>

In [8]:
import pandas as pd

In [9]:
def ler_arquivo(nome_arquivo):
    try:
        return pd.read_excel(f'bases/{nome_arquivo}.xlsx')
    except FileNotFoundError as e:
        return f'Erro: {e}'

In [10]:
df = ler_arquivo('dados de entregas')

SLA

In [11]:
df

,id_entrega,filial,cliente,status,descricao_entrega,tipo_servico,valor_frete,data_postagem,prazo_previsto,data_prevista,data_entrega,dias_atraso
0,3619,SC,Americanas,ENTREGUE,Extravio temporário,ECONÔMICO,25.16,2026-01-09 20:43:34.883,5,2026-01-14 20:43:34.883,2026-01-15 20:43:34.883,1
1,4850,RJ,Amazon,ENTREGUE,Entrega reagendada,NORMAL,38.17,2026-01-06 20:43:34.889,5,2026-01-11 20:43:34.889,2026-01-10 20:43:34.889,0
2,3232,MG,Magazine Luiza,EM TRÂNSITO,Cliente ausente no local,NORMAL,311.62,2026-02-03 20:43:34.881,1,2026-02-04 20:43:34.881,2026-02-05 20:43:34.881,1
3,3944,RS,Amazon,EM TRÂNSITO,Cliente ausente no local,NORMAL,65.46,2026-01-17 20:43:34.885,7,2026-01-24 20:43:34.885,2026-01-26 20:43:34.885,2
4,2633,SP,Amazon,EM TRÂNSITO,Problema operacional na rota,ECONÔMICO,104.62,2026-02-03 20:43:34.875,2,2026-02-05 20:43:34.875,2026-02-05 20:43:34.875,0
...,...,...,...,...,...,...,...,...,...,...,...,...
5195,3997,SC,Shopee,ENTREGUE,Entrega normal,NORMAL,38.12,2026-01-23 20:43:34.885,7,2026-01-30 20:43:34.885,2026-01-31 20:43:34.885,1
5196,3250,PR,Mercado Livre,ENTREGUE,Problema operacional na rota,ECONÔMICO,69.88,2026-01-19 20:43:34.881,2,2026-01-21 20:43:34.881,2026-01-19 20:43:34.881,0
5197,2834,PR,Magazine Luiza,EM TRÂNSITO,Extravio temporário,ECONÔMICO,152.43,2026-01-15 20:43:34.877,7,2026-01-22 20:43:34.877,2026-01-24 20:43:34.877,2
5198,507,MG,Amazon,EM TRÂNSITO,Entrega EXPRESSA,ECONÔMICO,27.43,2026-02-03 20:43:34.864,2,2026-02-05 20:43:34.864,2026-02-07 20:43:34.864,2
5199,714,RJ,Magazine Luiza,EM TRÂNSITO,Entrega reagendada,NORMAL,156.33,2026-01-14 20:43:34.865,1,2026-01-15 20:43:34.865,2026-01-19 20:43:34.865,4

In [15]:
# Total de entregas sem atraso
#shape [0] retornar a quantidade de entregas
sla_ok = df.loc[
    (df['dias_atraso'] == 0) & (df['status'] == 'ENTREGUE')
].shape[0]

# Total de entregas 
df_total_entregues = df.loc[
    df['status'] == 'ENTREGUE'
]

#Percentual SLA
sla_percentual = (sla_ok / df_total_entregues.shape[0]) * 100

round(sla_percentual,1)

37.2

KPI - Entregas atrasadas

In [13]:
# Total de entregas COM atraso
total_out_of_time = df.loc[
    (df['dias_atraso'] > 0) & (df['status'] == 'ENTREGUE')
].shape[0]

#Percentual SLA
sla_out_of_time = (total_out_of_time/ df_total_entregues) * 100


round(sla_out_of_time,1)

62.8

SLA - Identificando onde as operações funcionam melhor

In [17]:

sla_filial = df_total_entregues.groupby('filial')['dias_atraso'].mean()

sla_filial

filial
MG    1.841530
PR    1.917040
RJ    1.805195
RS    1.974886
SC    1.907449
SP    1.797647
Name: dias_atraso, dtype: float64

In [28]:

sla_filial = df_total_entregues.groupby('filial')['dias_atraso'].apply(
    lambda grupo: (grupo == 0).mean() * 100
).sort_values(ascending=False) #ordena do maior para o menor (Decrescente)

round(sla_filial,2).reset_index(name='% entregas no prazo')

  filial  % entregas no prazo
0     RJ                42.08
1     PR                38.34
2     MG                38.25
3     SP                35.76
4     RS                34.93
5     SC                34.76