Importando Libs

In [16]:
import pyodbc 
import pandas as pd

Criando conexão

In [ ]:
#conn = pyodbc.connect(
   # 'DRIVER={MongoDB ODBC 1.4.5 Unicode Driver};' \
    #'SERVER=biconnector.xoljv.mongodb.net:27015;' \
    #'DATABASE=bi_jadlog;' \
    #'UID=bijadlog?source=admin;' \
    #'PWD=N9QZHb1HjM0d16lg;' \
   # 'MARS_Connection=Yes'
#)

import os
senha = os.getenv('senha_bd_simples')

conn = pyodbc.connect(
    "DRIVER={SQL Server};" \
    "SERVER=den1.mssql7.gear.host;" \
    "DATABASE=vendasbicyclon;" \
    "UID=vendasbicyclon;" \
    f'PWD={senha};"\
    "MARS_Connection=Yes"
)

In [18]:
query = """
SELECT
    TABLE_SCHEMA,
    TABLE_NAME
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_TYPE = 'BASE TABLE' 
        ORDER BY TABLE_SCHEMA, TABLE_NAME

"""

df_tabelas = pd.read_sql(query,conn)
df_tabelas

C:\Users\erivan.junior\AppData\Local\Temp\ipykernel_7656\2548664148.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tabelas = pd.read_sql(query,conn)

  TABLE_SCHEMA      TABLE_NAME
0          dbo        clientes
1          dbo     itensPedido
2          dbo  linhasProdutos
3          dbo         pedidos
4          dbo        produtos
5          dbo       regionais
6          dbo     sysdiagrams
7          dbo      vendedores

Nome dos Clientes

In [21]:
query = """
SELECT
    nomeCliente
        FROM dbo.clientes 

"""

df_clientes = pd.read_sql(query,conn)
df_clientes

C:\Users\erivan.junior\AppData\Local\Temp\ipykernel_7656\3757928978.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_clientes = pd.read_sql(query,conn)

                 nomeCliente
0         Velocycle Emporium
1         Pedal & Gear Haven
2    CicloFusion Marketplace
3         BiciMondo Ventures
4   SpinScape Bikes & Beyond
5         CyclaVista Cyclery
6  RollRight Wheels Emporium
7        GearSpin Provisions
8              BikeHub Oasis
9        PedalCraft Boutique

Produtos com valor > 2000 e descrição preenchida

In [28]:
query = """
SELECT
    nomeProduto,
    descricaoProduto,
    precoUnitario
        FROM dbo.produtos 
        WHERE precoUnitario >= 2000

"""

df_produtos = pd.read_sql(query,conn)
df_produtos

C:\Users\erivan.junior\AppData\Local\Temp\ipykernel_7656\335902363.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_produtos = pd.read_sql(query,conn)

,nomeProduto,descricaoProduto,precoUnitario
0,Summit Seeker 2000,Mountain Bike com suspens?o dianteira e traseira,2499.0
1,Velocity Racer 3000,Road Bike de carbono leve,3499.0
2,E-Power Cruiser 6000,Electric Bike com motor de pedal assistido,2399.0
3,Junior Adventurer 8000,Kids Bike para crian?as de 6 a 9 anos,2999.0
4,Expedition Voyager 11000,Touring Bike para viagens longas e aventuras,2799.0